version: '2'
services:
  frontend:
    build: ./frontend
    restart: always
    expose:
      - "80"
  proxy:
    build: ./haproxy
    restart: always
    depends_on:
      - frontend
      - data
    ports:
      - "80:80"
  data:
    build: ./data
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    privileged: true
