version: '2'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    expose:
      - "80"
  proxy:
    container_name: proxy
    build: ./haproxy
    restart: always
    depends_on:
      - frontend
      - data
    ports:
      - "80:80"
  data:
    container_name: data
    build: ./data
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - data-volume:/src/data
    environment:
      VOLUME_PATH: '/src/data'
      METRICS_FOLDER_NAME: 'metrics_collection'

volumes:
  data-volume:
    name: data-volume