version: '2'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    network_mode: host
  proxy:
    container_name: proxy
    build: ./haproxy
    restart: always
    depends_on:
      - frontend
      - data
    network_mode: host
  data:
    container_name: data
    build: ./data
    restart: always
    privileged: true
    volumes:
      - data-volume:/src/data
    env_file:
      - .env
    network_mode: host

volumes:
  data-volume:
    name: data-volume